=== UO277938/tfg-xml/backend/xmlvalidator/src/main/resources/xml/articulo.dtd
<!-- REUTILIZABLE -->
<!ENTITY % contenidoElemento
        "parrafo |
        titulo |
        lista |
        listaDefiniciones |
        tabla |
        multimedia |
        figura |
        cita |
        formulario |
        seccion |
        articulo |
        aparte |
        contenedor |
        detalles |
        dialogo |
        preformateado">

<!ENTITY % contenidoTexto
        "(#PCDATA |
        codigo |
        enlace |
        saltoLinea)*">

<!-- ESTRUCTURA -->
<!ELEMENT documento (metadatos, cuerpo)>
<!-- METADATOS -->
<!ELEMENT metadatos (tituloHTML, autor, fecha, resumen?)>
<!ELEMENT tituloHTML (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT resumen %contenidoTexto;>

<!-- SECCIONES -->
<!ELEMENT cuerpo (encabezado?, navegacion?, aparte?, principal?, pie?)>

<!ELEMENT articulo (titulo?, (%contenidoElemento;)*)>
<!ELEMENT seccion (titulo?, (%contenidoElemento;)*)>
<!ELEMENT navegacion (enlace | lista)*>
<!ELEMENT aparte (titulo?, (%contenidoElemento;)*)>
<!ELEMENT encabezado (titulo?, (%contenidoElemento;)*)>
<!ELEMENT pie ((%contenidoElemento;)*)>
<!ELEMENT contenedor ((%contenidoElemento;)*)>

<!ELEMENT principal ((%contenidoElemento;)*)>


<!-- CONTENIDO -->
<!ELEMENT titulo %contenidoTexto;>
<!ATTLIST titulo nivel (1|2|3|4|5|6) #REQUIRED>
<!ELEMENT parrafo %contenidoTexto;>

<!-- TEXTO -->
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT preformateado (#PCDATA)>
<!ELEMENT cita %contenidoTexto;>
<!ATTLIST cita autor CDATA #IMPLIED>
<!ELEMENT saltoLinea EMPTY>

<!-- LISTA -->
<!ELEMENT lista (elementoLista+)>
<!ATTLIST lista
    tipo (ordenada | desordenada) "desordenada">
<!ELEMENT elementoLista %contenidoTexto;>

<!ELEMENT listaDefiniciones (termino, definicion)+>
<!ELEMENT termino %contenidoTexto;>
<!ELEMENT definicion %contenidoTexto;>

<!-- TABLA -->
<!ELEMENT tabla (leyenda?, cabecera?, cuerpoTabla, pieTabla?)>

<!ELEMENT leyenda %contenidoTexto;>
<!ELEMENT cabecera (fila+)>
<!ELEMENT cuerpoTabla (fila+)>
<!ELEMENT pieTabla (fila+)>

<!ELEMENT fila (celda | celdaCabecera)+>
<!ELEMENT celda %contenidoTexto;>
<!ATTLIST celda
        colspan CDATA #IMPLIED
        rowspan CDATA #IMPLIED>
<!ELEMENT celdaCabecera %contenidoTexto;>
<!ATTLIST celdaCabecera
        colspan CDATA #IMPLIED
        rowspan CDATA #IMPLIED>

<!-- FORMULARIO -->
<!ELEMENT formulario (
        etiqueta |
        entrada |
        boton |
        areaTexto |
        seleccion |
        grupoFormulario |
        salida
        )*>
<!ATTLIST formulario
        action CDATA #IMPLIED
        method (get | post) "get">

<!ELEMENT grupoFormulario (
        leyenda,
        (etiqueta |
        entrada |
        boton |
        areaTexto |
        seleccion |
        salida)+)>

<!ELEMENT etiqueta %contenidoTexto;>
<!ATTLIST etiqueta
        para CDATA #IMPLIED>

<!ELEMENT entrada EMPTY>
<!ATTLIST entrada
        tipo (
            text |
            password |
            email |
            number |
            date |
            time |
            datetime |
            url |
            tel |
            search |
            checkbox |
            radio |
            file |
            color |
            range |
            hidden |
            submit |
            reset
            ) "text"
        nombre CDATA #IMPLIED
        valor CDATA #IMPLIED
        placeholder CDATA #IMPLIED
        requerido (true | false) "false"
        deshabilitado (true | false) "false">

<!ELEMENT boton %contenidoTexto;>
<!ATTLIST boton
        tipo (button | submit | reset) "submit">
<!ELEMENT areaTexto (#PCDATA)>
<!ELEMENT seleccion (opcion+)>
<!ATTLIST seleccion
        nombre CDATA #IMPLIED
        requerido (true | false) "false">
<!ELEMENT opcion (#PCDATA)>
<!ATTLIST opcion
        valor CDATA #IMPLIED
        seleccionado (true|false) "false">
<!ELEMENT salida %contenidoTexto;>

<!-- MULTIMEDIA -->
<!ELEMENT multimedia EMPTY>
<!ATTLIST multimedia
        tipo (imagen | video | audio) #REQUIRED
        src CDATA #REQUIRED
        alt CDATA #IMPLIED
        controles (true | false) "false"
        autoplay (true | false) "false"
        loop (true | false) "false"
        muted (true | false) "false"
        poster CDATA #IMPLIED
        ancho CDATA #IMPLIED
        alto CDATA #IMPLIED>

<!ELEMENT enlace (#PCDATA)>
<!ATTLIST enlace
    href CDATA #REQUIRED
    target CDATA #IMPLIED>

<!ELEMENT figura (multimedia, leyenda?)>

<!-- INTERACTIVO -->
<!ELEMENT detalles (resumenDetalles, (%contenidoElemento;)*)>
<!ELEMENT resumenDetalles %contenidoTexto;>
<!ELEMENT dialogo ((%contenidoElemento;)*)>

=== UO277938/tfg-xml/backend/xmlvalidator/src/main/resources/xml/ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE articulo SYSTEM "articulo.dtd">

<articulo>

    <metadatos>
        <titulo>Introducción a XML</titulo>
        <autor>Fernando</autor>
        <fecha>2026-03-16</fecha>
        <resumen>Resumen de XML</resumen>
    </metadatos>

    <contenido>

        <seccion>
            <tituloSeccion>¿Qué es XML?</tituloSeccion>
            <parrafo>
                XML es un lenguaje de marcado utilizado para estructurar datos.
            </parrafo>
        </seccion>

        <seccion>
            <tituloSeccion>Ventajas</tituloSeccion>

            <parrafo>
                XML es extensible y legible.
            </parrafo>

            <lista>
                <elementoLista>Extensible</elementoLista>
                <elementoLista>Portable</elementoLista>
                <elementoLista>Legible</elementoLista>
            </lista>

        </seccion>

    </contenido>

</articulo>
